export type Lang = "it" | "en";

const it = {
  nav: {
    items: [
      "Il Progetto",
      "Statistiche",
      "Esplora Dizionario",
      "Interrogazioni",
      "Costruisci Dizionario",
      "Risultati Scientifici",
      "Contatti",
    ],
    reservedAria: (item: string) => `${item}, area riservata con autenticazione`,
    reservedTitle: "Area riservata: è richiesta una password",
    mainAria: "Navigazione principale",
    versionTitle: (version: string) => `Versione dell’interfaccia ${version}`,
    switchAria: "Selezione della lingua",
  },
  header: {
    eyebrow: "Ricerca Linguistica e Innovazione Sociale",
    partnerAria: "Partner del progetto",
  },
  workspace: {
    sectionAria: "Annotazione interviste",
    kicker: "INSERISCI E ANNOTA",
    intro: "Carica un’intervista e seleziona parole o frasi per annotarla.",
  },
  archive: {
    heading: "ARCHIVIO",
    title: "Interviste",
    uploadAria: "Carica più interviste in bulk",
    uploadTitle: "Carica più interviste",
    deleteAria: "Elimina l’intervista visualizzata",
    reloadAria: "Ricarica archivio da LexO-server",
    reloadTitle: "Ricarica archivio",
    searchPlaceholder: "Cerca intervista…",
    searchAria: "Cerca intervista per nome del file",
    loading: "Caricamento da LexO-server…",
    unavailable: "Archivio non disponibile",
    emptySearch: "Nessuna intervista trovata.",
    serverStats: (tokens: string, sentences: number, annotations: number) =>
      `${tokens} token · ${sentences} frasi · ${annotations} annotazioni`,
    localStats: (chars: string, annotations: number) =>
      `${chars} caratteri · ${annotations} annotazioni`,
    deleteConfirmTitle: (name: string) => `Eliminare l’intervista “${name}”?`,
    deleteConfirmBody: "Verranno eliminati il testo e le attestazioni associate. L’operazione non può essere annullata.",
    deleteSuccess: (name: string) => `Intervista “${name}” eliminata.`,
    deleteError: (detail: string) => `L’intervista non è stata eliminata: ${detail}`,
    deleteNotAllowed: "Solo le interviste caricate su LexO-server possono essere eliminate.",
    deleteRejected: "LexO-server non ha eliminato l’intervista",
    bulkPartial: (loaded: number, failed: number, detail: string) =>
      `Importazione parziale: ${loaded} file caricati, ${failed} non riusciti${detail ? `. ${detail}` : "."}`,
    bulkError: (detail: string) => `Errore durante l’importazione bulk: ${detail}`,
    bulkNoJob: "LexO-server non ha restituito l’identificativo del bulk",
    bulkNotReady: "I testi convertiti non sono ancora disponibili nell’archivio",
    bulkNoText: "Nessun testo del bulk è stato convertito",
    bulkAttestationsPartial: (count: number, detail: string) =>
      `${count} attestazioni non salvate: ${detail}`,
    bulkTimeout: "Tempo massimo superato durante l’importazione bulk",
    loadError: (detail: string) => `Impossibile caricare l’archivio (${detail}).`,
    selectAria: "Attiva o disattiva la selezione multipla delle interviste",
    selectTitle: "Seleziona interviste da eliminare",
    selectedCount: (n: number) => `${n} selezionate`,
    fileCount: (n: number) => `${n} interviste`,
    selectFirst: "Seleziona almeno una intervista",
    selectAll: "Tutte",
    clearSelection: "Nessuna",
    bulkDeleteConfirmTitle: (n: number) => `Eliminare ${n} interviste?`,
    bulkDeleteConfirmBody: "Verranno eliminati i testi e tutte le annotazioni associate. L’operazione non può essere annullata.",
    bulkDeleteActiveWarning: "Attenzione: è inclusa l’intervista correntemente aperta.",
    bulkDeleteProgress: (deleted: number, total: number) => `Eliminate ${deleted} di ${total}…`,
    uploadProgress: (uploaded: number, total: number) => `Caricati ${uploaded} di ${total}…`,
    bulkDeleteSuccess: (n: number) => `${n} interviste eliminate.`,
    bulkDeletePartial: (deleted: number, failed: number, detail: string) =>
      `Eliminate ${deleted} interviste, ${failed} non riuscite${detail ? `. ${detail}` : "."}`,
    bulkDeleteError: (detail: string) => `Errore durante l’eliminazione bulk: ${detail}`,
  },
  document: {
    noInterview: "Nessuna intervista",
    textLoadError: (detail: string) => `Impossibile caricare il testo (${detail}).`,
    loadingText: "Caricamento testo…",
    chars: (n: string) => `${n} caratteri`,
    descriptionAria: (description: string) => `Descrizione: ${description}`,
    loadingInterview: "Caricamento intervista…",
    textUnavailable: "Testo non disponibile",
    retry: "Riprova",
    locusHint: "Modifica locus: trascina le maniglie oppure seleziona un nuovo intervallo",
    editHint: "Modalità modifica attestazione",
    selectHint: "Seleziona una porzione di testo con il mouse",
    savingAria: "Salvataggio annotazione in corso",
    countAll: (n: number) => `${n} annotazioni`,
    countFiltered: (filtered: number, total: number) => `${filtered} di ${total} annotazioni · Concetto`,
    filterRemoveTitle: "Rimuovi il filtro concetto",
    editAria: (label: string) => `Modifica attestazione: ${label}`,
    editTitle: "Modifica attestazione",
    locusSaveAria: "Salva i nuovi limiti dell’evidenziazione",
    locusEditAria: "Modifica i limiti dell’evidenziazione",
    locusSaveTitle: "Salva nuovo start ed end",
    locusEditTitle: "Modifica start ed end",
    eraseAria: "Elimina l’intera attestazione",
    eraseTitle: "Elimina attestazione e concetti associati",
  },
  concepts: {
    sidebarAria: "Repertorio dei concetti",
    heading: "REPERTORIO",
    title: "Concetti",
    addAria: "Aggiungi lexical concept",
    addTitle: "Aggiungi lexical concept",
    creatingAria: "Creazione del concetto in corso",
    renamingAria: "Rinomina del concetto in corso",
    reloadAria: "Ricarica concetti da LexO-server",
    reloadTitle: "Ricarica concetti",
    count: (n: number) => `${n} voci`,
    introEdit: "Modifica i concetti associati o i loro attributi. Il tipo narrativo/paradigmatico dei concetti esistenti non può essere cambiato.",
    introSelect: "Seleziona uno o più concetti, poi scegli entrata lessicale e attributi in ciascun pannello.",
    introIdle: "Seleziona una parte dell’intervista per associare i concetti.",
    searchPlaceholder: "Cerca concetto…",
    searchAria: "Cerca concetto per label",
    loading: "Caricamento da LexO-server…",
    unavailable: "Repertorio non disponibile",
    newPlaceholder: "Scrivi il nome del concetto",
    newNameAria: "Nome del nuovo lexical concept",
    confirmCreateAria: "Conferma creazione",
    cancelCreateAria: "Annulla creazione",
    editAria: (label: string) => `Modifica ${label}`,
    confirmRenameAria: "Conferma rinomina",
    cancelRenameAria: "Annulla rinomina",
    clickSelect: "Clic per selezionare il concetto",
    clickFilter: "Clic per filtrare le annotazioni per concetto",
    emptyAll: "Nessun concetto trovato.",
    emptyFilter: "Nessun concetto corrispondente.",
    menuAria: "Menu concetto",
    menuDelete: "Elimina",
    deleteConfirmTitle: (label: string) => `Eliminare il concetto “${label}”?`,
    deleteConfirmBody: "Il concetto verrà rimosso dal repertorio. L’operazione non può essere annullata.",
    exists: (label: string) => `Esiste già un concetto chiamato “${label}”.`,
    created: (label: string) => `Concetto “${label}” creato correttamente.`,
    createError: (detail: string) => `Il concetto non è stato creato: ${detail}`,
    renamed: (label: string) => `Concetto rinominato in “${label}”.`,
    renameError: (detail: string) => `La label non è stata modificata a causa di un errore in LexO-server: ${detail}`,
    inUse: (label: string) => `Il concetto “${label}” è usato e non può essere eliminato.`,
    deleted: (label: string) => `Concetto “${label}” eliminato.`,
    deleteError: (detail: string) => `Il concetto non è stato eliminato: ${detail}`,
    loadError: (detail: string) => `Impossibile caricare i concetti (${detail})`,
    unknownError: "errore sconosciuto",
  },
  entry: {
    legend: "Entrata lessicale",
    aria: (label: string) => `Entrata lessicale per ${label}`,
    loading: "Caricamento…",
    choose: "Scegli un’entrata…",
    none: "Nessuna entrata associata",
    unavailable: "Entrate non disponibili",
    retry: "Riprova",
    sensesLoading: "Caricamento metadata dei sensi…",
    sensesError: "Metadata non disponibili.",
    noSenses: "Nessun senso narrativo o paradigmatico trovato.",
    noNarrative: "Senso narrativo non disponibile.",
    noParadigmatic: "Senso paradigmatico non disponibile.",
  },
  panels: {
    relationLegend: "Relazione",
    polarityLegend: "Polarità",
    polarityAria: (label: string) => `Polarità ${label}`,
    definitionLegend: "Tipo di definizione",
    definitionAria: (label: string) => `Tipo di definizione: ${label}`,
    evidenceLegend: "Tipo di evidenza",
    usageLegend: "Modi d’uso",
    usageAria: (label: string) => `Modo d’uso per ${label}`,
    noteLegend: "Note",
    noteAria: (label: string) => `Note per ${label}`,
    notePlaceholder: "Aggiungi una nota…",
  },
  options: {
    relation: { paradigmatico: "Paradigmatico", narrativo: "Narrativo" },
    polarity: { negative: "Negative", neutral: "Neutral", positive: "Positive" },
    definition: {
      sinonimo: "Sinonimo",
      parafrasi: "Parafrasi",
      "esempio-prototipo": "Esempio prototipo",
      "associazione-concettuale": "Associazione concettuale",
    },
    evidence: { nessuno: "Nessuno", attestato: "Attestato", inferito: "Inferito" },
    usageNone: "Nessuno",
  },
  action: {
    save: "Salva annotazione",
    confirm: "Conferma modifiche",
    savingAria: "Salvataggio in corso",
    oneSelected: "concetto selezionato",
    manySelected: "concetti selezionati",
    editCompleteNew: "Completa i dati obbligatori dei nuovi concetti",
    editModify: "Modifica concetti o attributi",
    createComplete: "Completa entrata, relazione e attributi di ogni concetto",
    createChoose: "Scegli almeno un concetto",
  },
  modals: {
    kicker: "ELIMINAZIONE",
    cancel: "Annulla",
    delete: "Elimina",
    attestationTitle: "Eliminare l’attestazione?",
    attestationBody: (text: string) =>
      `Verranno eliminate l’attestazione “${text}” e i concetti ad essa associati. L’operazione non può essere annullata.`,
    interviewTitle: (name: string) => `Eliminare l’intervista “${name}”?`,
    interviewBody: "Verranno eliminati il testo e le attestazioni associate. L’operazione non può essere annullata.",
    growlClose: "Chiudi messaggio",
    dirtyKicker: "MODIFICHE NON SALVATE",
    dirtyTitle: "Scartare le modifiche?",
    dirtyBody: "L’annotazione corrente ha modifiche non salvate: procedendo verranno perse.",
    dirtyConfirm: "Scarta e procedi",
    passwordKicker: "AREA RISERVATA",
    passwordTitle: "Costruisci Dizionario",
    passwordBody: "L’area di annotazione è riservata: inserisci la password per accedere.",
    passwordPlaceholder: "Password",
    passwordAria: "Password dell’area riservata",
    passwordConfirm: "Accedi",
    passwordError: "Password non corretta.",
  },
  messages: {
    attestationsLoadError: (detail: string) => `Impossibile caricare le attestazioni: ${detail}`,
    senseMetadataError: (detail: string) => `Impossibile caricare i metadata dei sensi: ${detail}`,
    createNeedOptions: "Scegli paradigmatico o narrativo e completa gli attributi richiesti per ogni concetto.",
    createNoContext: "Non è possibile creare l’attestazione: l’intervista non contiene l’IRI del nif:Context.",
    createConceptGone: "Non è possibile creare l’attestazione: uno dei concetti selezionati non è più disponibile.",
    createPartialSenses: (failed: number, labels: string) =>
      `Attestazione creata, ma non è stato possibile aggiornare ${failed} concetti narrativi (${labels}).`,
    createReloadError: (detail: string) => `Attestazione creata, ma non è stato possibile ricaricare l’elenco (${detail}).`,
    saved: "Annotazione salvata.",
    saveError: (detail: string) => `Errore durante il salvataggio dell’annotazione: ${detail}`,
    locusNoText: "Non è possibile modificare il locus: mancano i dati del testo su LexO-server.",
    locusNoAttestations: "Non è possibile modificare il locus: mancano gli IRI delle attestazioni selezionate.",
    locusSaved: (start: number, end: number) => `Nuovo locus salvato: start ${start}, end ${end}.`,
    locusError: (detail: string) => `Errore durante la modifica del locus: ${detail}`,
    updateNeedOptions: "Completa entrata, relazione e attributi obbligatori dei nuovi concetti.",
    updateNoText: "Non è possibile modificare l’attestazione: mancano i dati del testo su LexO-server.",
    updateNoLocus: "Non è possibile modificare l’attestazione: manca l’IRI del locus.",
    updateConceptGone: "Uno dei nuovi concetti selezionati non è più disponibile.",
    updatePartialFailures: (failed: number, total: number, details: string) =>
      `${failed} di ${total} aggiornamenti non riusciti: ${details}`,
    updateRemoveError: (detail: string) => `Rimozione: ${detail}`,
    updateAddError: (detail: string) => `Aggiunta: ${detail}`,
    updateSenseLinkError: (label: string, detail: string) => `Collegamento del senso per ${label}: ${detail}`,
    updateMetadataError: (detail: string) => `Aggiornamento metadati: ${detail}`,
    updated: "Modifiche all’attestazione salvate.",
    updateError: (detail: string) => `Errore durante la modifica dell’attestazione: ${detail}`,
    deleteNoContext: "Non è possibile eliminare l’attestazione: l’intervista non contiene l’IRI del nif:Context.",
    deleteNoLocus: "Non è possibile eliminare l’attestazione: il servizio non ha restituito l’IRI del locus.",
    deleted: "Attestazione eliminata.",
    deleteError: (detail: string) => `Errore durante l’eliminazione dell’attestazione: ${detail}`,
  },
};

export type Dict = typeof it;

const en: Dict = {
  nav: {
    items: [
      "The Project",
      "Statistics",
      "Explore Dictionary",
      "Queries",
      "Dictionary Builder",
      "Scientific Results",
      "Contacts",
    ],
    reservedAria: (item: string) => `${item}, restricted area requiring authentication`,
    reservedTitle: "Restricted area: password required",
    mainAria: "Main navigation",
    versionTitle: (version: string) => `Interface version ${version}`,
    switchAria: "Language selection",
  },
  header: {
    eyebrow: "Linguistic Research and Social Innovation",
    partnerAria: "Project partners",
  },
  workspace: {
    sectionAria: "Interview annotation",
    kicker: "UPLOAD AND ANNOTATE",
    intro: "Upload an interview and select words or phrases to annotate it.",
  },
  archive: {
    heading: "ARCHIVE",
    title: "Interviews",
    uploadAria: "Bulk upload interviews",
    uploadTitle: "Bulk upload interviews",
    deleteAria: "Delete the displayed interview",
    reloadAria: "Reload archive from LexO-server",
    reloadTitle: "Reload archive",
    searchPlaceholder: "Search interviews…",
    searchAria: "Search interviews by file name",
    loading: "Loading from LexO-server…",
    unavailable: "Archive unavailable",
    emptySearch: "No interview found.",
    serverStats: (tokens: string, sentences: number, annotations: number) =>
      `${tokens} tokens · ${sentences} sentences · ${annotations} annotations`,
    localStats: (chars: string, annotations: number) =>
      `${chars} characters · ${annotations} annotations`,
    deleteConfirmTitle: (name: string) => `Delete interview “${name}”?`,
    deleteConfirmBody: "The text and its attestations will be deleted. This action cannot be undone.",
    deleteSuccess: (name: string) => `Interview “${name}” deleted.`,
    deleteError: (detail: string) => `The interview was not deleted: ${detail}`,
    deleteNotAllowed: "Only interviews stored on LexO-server can be deleted.",
    deleteRejected: "LexO-server did not delete the interview",
    bulkPartial: (loaded: number, failed: number, detail: string) =>
      `Partial import: ${loaded} files uploaded, ${failed} failed${detail ? `. ${detail}` : "."}`,
    bulkError: (detail: string) => `Error during bulk import: ${detail}`,
    bulkNoJob: "LexO-server did not return the bulk identifier",
    bulkNotReady: "The converted texts are not yet available in the archive",
    bulkNoText: "No text from the bulk was converted",
    bulkAttestationsPartial: (count: number, detail: string) =>
      `${count} attestations not saved: ${detail}`,
    bulkTimeout: "Maximum time exceeded during bulk import",
    loadError: (detail: string) => `Unable to load the archive (${detail}).`,
    selectAria: "Toggle multi-selection of interviews",
    selectTitle: "Select interviews to delete",
    selectedCount: (n: number) => `${n} selected`,
    fileCount: (n: number) => `${n} interviews`,
    selectFirst: "Select at least one interview",
    selectAll: "All",
    clearSelection: "Clear",
    bulkDeleteConfirmTitle: (n: number) => `Delete ${n} interviews?`,
    bulkDeleteConfirmBody: "The texts and all their annotations will be deleted. This action cannot be undone.",
    bulkDeleteActiveWarning: "Warning: the currently open interview is included.",
    bulkDeleteProgress: (deleted: number, total: number) => `Deleted ${deleted} of ${total}…`,
    uploadProgress: (uploaded: number, total: number) => `Uploaded ${uploaded} of ${total}…`,
    bulkDeleteSuccess: (n: number) => `${n} interviews deleted.`,
    bulkDeletePartial: (deleted: number, failed: number, detail: string) =>
      `${deleted} interviews deleted, ${failed} failed${detail ? `. ${detail}` : "."}`,
    bulkDeleteError: (detail: string) => `Error during bulk deletion: ${detail}`,
  },
  document: {
    noInterview: "No interview",
    textLoadError: (detail: string) => `Unable to load the text (${detail}).`,
    loadingText: "Loading text…",
    chars: (n: string) => `${n} characters`,
    descriptionAria: (description: string) => `Description: ${description}`,
    loadingInterview: "Loading interview…",
    textUnavailable: "Text unavailable",
    retry: "Retry",
    locusHint: "Locus editing: drag the handles or select a new range",
    editHint: "Annotation editing mode",
    selectHint: "Select a portion of text with the mouse",
    savingAria: "Saving annotation",
    countAll: (n: number) => `${n} annotations`,
    countFiltered: (filtered: number, total: number) => `${filtered} of ${total} annotations · Concept`,
    filterRemoveTitle: "Remove concept filter",
    editAria: (label: string) => `Edit attestation: ${label}`,
    editTitle: "Edit attestation",
    locusSaveAria: "Save the new highlight boundaries",
    locusEditAria: "Edit the highlight boundaries",
    locusSaveTitle: "Save new start and end",
    locusEditTitle: "Edit start and end",
    eraseAria: "Delete the entire attestation",
    eraseTitle: "Delete attestation and associated concepts",
  },
  concepts: {
    sidebarAria: "Concept repertory",
    heading: "REPERTORY",
    title: "Concepts",
    addAria: "Add lexical concept",
    addTitle: "Add lexical concept",
    creatingAria: "Creating concept",
    renamingAria: "Renaming concept",
    reloadAria: "Reload concepts from LexO-server",
    reloadTitle: "Reload concepts",
    count: (n: number) => `${n} entries`,
    introEdit: "Edit the associated concepts or their attributes. The narrative/paradigmatic type of existing concepts cannot be changed.",
    introSelect: "Select one or more concepts, then choose the lexical entry and attributes in each panel.",
    introIdle: "Select part of the interview to associate concepts.",
    searchPlaceholder: "Search concepts…",
    searchAria: "Search concepts by label",
    loading: "Loading from LexO-server…",
    unavailable: "Repertory unavailable",
    newPlaceholder: "Type the concept name",
    newNameAria: "Name of the new lexical concept",
    confirmCreateAria: "Confirm creation",
    cancelCreateAria: "Cancel creation",
    editAria: (label: string) => `Edit ${label}`,
    confirmRenameAria: "Confirm rename",
    cancelRenameAria: "Cancel rename",
    clickSelect: "Click to select the concept",
    clickFilter: "Click to filter annotations by concept",
    emptyAll: "No concept found.",
    emptyFilter: "No matching concept.",
    menuAria: "Concept menu",
    menuDelete: "Delete",
    deleteConfirmTitle: (label: string) => `Delete concept “${label}”?`,
    deleteConfirmBody: "The concept will be removed from the repertory. This action cannot be undone.",
    exists: (label: string) => `A concept named “${label}” already exists.`,
    created: (label: string) => `Concept “${label}” created successfully.`,
    createError: (detail: string) => `The concept was not created: ${detail}`,
    renamed: (label: string) => `Concept renamed to “${label}”.`,
    renameError: (detail: string) => `The label was not changed due to a LexO-server error: ${detail}`,
    inUse: (label: string) => `The concept “${label}” is in use and cannot be deleted.`,
    deleted: (label: string) => `Concept “${label}” deleted.`,
    deleteError: (detail: string) => `The concept was not deleted: ${detail}`,
    loadError: (detail: string) => `Unable to load concepts (${detail})`,
    unknownError: "unknown error",
  },
  entry: {
    legend: "Lexical entry",
    aria: (label: string) => `Lexical entry for ${label}`,
    loading: "Loading…",
    choose: "Choose an entry…",
    none: "No associated entry",
    unavailable: "Entries unavailable",
    retry: "Retry",
    sensesLoading: "Loading sense metadata…",
    sensesError: "Metadata unavailable.",
    noSenses: "No narrative or paradigmatic sense found.",
    noNarrative: "Narrative sense unavailable.",
    noParadigmatic: "Paradigmatic sense unavailable.",
  },
  panels: {
    relationLegend: "Relation",
    polarityLegend: "Polarity",
    polarityAria: (label: string) => `Polarity ${label}`,
    definitionLegend: "Definition type",
    definitionAria: (label: string) => `Definition type: ${label}`,
    evidenceLegend: "Evidence type",
    usageLegend: "Usage modes",
    usageAria: (label: string) => `Usage mode for ${label}`,
    noteLegend: "Notes",
    noteAria: (label: string) => `Notes for ${label}`,
    notePlaceholder: "Add a note…",
  },
  options: {
    relation: { paradigmatico: "Paradigmatic", narrativo: "Narrative" },
    polarity: { negative: "Negative", neutral: "Neutral", positive: "Positive" },
    definition: {
      sinonimo: "Synonym",
      parafrasi: "Paraphrase",
      "esempio-prototipo": "Prototype example",
      "associazione-concettuale": "Conceptual association",
    },
    evidence: { nessuno: "None", attestato: "Attested", inferito: "Inferred" },
    usageNone: "None",
  },
  action: {
    save: "Save annotation",
    confirm: "Confirm changes",
    savingAria: "Saving",
    oneSelected: "concept selected",
    manySelected: "concepts selected",
    editCompleteNew: "Complete the required data of the new concepts",
    editModify: "Edit concepts or attributes",
    createComplete: "Complete entry, relation and attributes of each concept",
    createChoose: "Choose at least one concept",
  },
  modals: {
    kicker: "DELETION",
    cancel: "Cancel",
    delete: "Delete",
    attestationTitle: "Delete this attestation?",
    attestationBody: (text: string) =>
      `The attestation “${text}” and its associated concepts will be deleted. This action cannot be undone.`,
    interviewTitle: (name: string) => `Delete interview “${name}”?`,
    interviewBody: "The text and its attestations will be deleted. This action cannot be undone.",
    growlClose: "Close message",
    dirtyKicker: "UNSAVED CHANGES",
    dirtyTitle: "Discard changes?",
    dirtyBody: "The current annotation has unsaved changes: continuing will lose them.",
    dirtyConfirm: "Discard and proceed",
    passwordKicker: "RESTRICTED AREA",
    passwordTitle: "Build Dictionary",
    passwordBody: "The annotation area is restricted: enter the password to continue.",
    passwordPlaceholder: "Password",
    passwordAria: "Restricted area password",
    passwordConfirm: "Sign in",
    passwordError: "Incorrect password.",
  },
  messages: {
    attestationsLoadError: (detail: string) => `Unable to load attestations: ${detail}`,
    senseMetadataError: (detail: string) => `Unable to load sense metadata: ${detail}`,
    createNeedOptions: "Choose paradigmatic or narrative and complete the required attributes for each concept.",
    createNoContext: "Cannot create the attestation: the interview has no nif:Context IRI.",
    createConceptGone: "Cannot create the attestation: one of the selected concepts is no longer available.",
    createPartialSenses: (failed: number, labels: string) =>
      `Attestation created, but ${failed} narrative concepts could not be updated (${labels}).`,
    createReloadError: (detail: string) => `Attestation created, but the list could not be reloaded (${detail}).`,
    saved: "Annotation saved.",
    saveError: (detail: string) => `Error while saving the annotation: ${detail}`,
    locusNoText: "Cannot edit the locus: text data is missing on LexO-server.",
    locusNoAttestations: "Cannot edit the locus: the selected attestations have no IRIs.",
    locusSaved: (start: number, end: number) => `New locus saved: start ${start}, end ${end}.`,
    locusError: (detail: string) => `Error while editing the locus: ${detail}`,
    updateNeedOptions: "Complete the entry, relation and required attributes of the new concepts.",
    updateNoText: "Cannot edit the attestation: text data is missing on LexO-server.",
    updateNoLocus: "Cannot edit the attestation: the locus IRI is missing.",
    updateConceptGone: "One of the newly selected concepts is no longer available.",
    updatePartialFailures: (failed: number, total: number, details: string) =>
      `${failed} of ${total} updates failed: ${details}`,
    updateRemoveError: (detail: string) => `Removal: ${detail}`,
    updateAddError: (detail: string) => `Addition: ${detail}`,
    updateSenseLinkError: (label: string, detail: string) => `Sense linking for ${label}: ${detail}`,
    updateMetadataError: (detail: string) => `Metadata update: ${detail}`,
    updated: "Attestation changes saved.",
    updateError: (detail: string) => `Error while editing the attestation: ${detail}`,
    deleteNoContext: "Cannot delete the attestation: the interview has no nif:Context IRI.",
    deleteNoLocus: "Cannot delete the attestation: the service did not return the locus IRI.",
    deleted: "Attestation deleted.",
    deleteError: (detail: string) => `Error while deleting the attestation: ${detail}`,
  },
};

export const dictionaries: Record<Lang, Dict> = { it, en };

export function detectInitialLang(): Lang {
  try {
    const stored = window.localStorage.getItem("fi-lang");
    if (stored === "it" || stored === "en") return stored;
  } catch {
  }
  return typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("en")
    ? "en"
    : "it";
}
