export type Lang = "it" | "en";

const it = {
  nav: {
    items: [
      "Il Progetto",
      "Statistiche",
      "Esplora Dizionario",
      "Esplora Dizionario",
      "Costruisci Dizionario",
      "Risultati Scientifici",
      "Contatti",
    ],
    reservedAria: (item: string) => `${item}, area riservata con autenticazione`,
    reservedTitle: "Area riservata: è richiesta una password",
    mainAria: "Navigazione principale",
    versionTitle: (version: string) => `Versione dell’interfaccia ${version}`,
    switchAria: "Selezione della lingua",
  },
  header: {
    eyebrow: "Ricerca Linguistica e Innovazione Sociale",
    partnerAria: "Partner del progetto",
  },
  workspace: {
    sectionAria: "Annotazione interviste",
  },
  archive: {
    title: "Interviste",
    uploadAria: "Carica più interviste in bulk",
    uploadTitle: "Carica più interviste",
    deleteAria: "Elimina l’intervista visualizzata",
    reloadAria: "Ricarica archivio da LexO-server",
    reloadTitle: "Ricarica archivio",
    searchPlaceholder: "Cerca intervista…",
    searchAria: "Cerca intervista per nome del file",
    loading: "Caricamento da LexO-server…",
    unavailable: "Archivio non disponibile",
    emptySearch: "Nessuna intervista trovata.",
    serverStats: (tokens: string, sentences: number, annotations: number) =>
      `${tokens} token · ${sentences} frasi · ${annotations} annotazioni`,
    localStats: (chars: string, annotations: number) =>
      `${chars} caratteri · ${annotations} annotazioni`,
    deleteConfirmTitle: (name: string) => `Eliminare l’intervista “${name}”?`,
    deleteConfirmBody: "Verranno eliminati il testo e le attestazioni associate. L’operazione non può essere annullata.",
    deleteSuccess: (name: string) => `Intervista “${name}” eliminata.`,
    deleteError: (detail: string) => `L’intervista non è stata eliminata: ${detail}`,
    deleteNotAllowed: "Solo le interviste caricate su LexO-server possono essere eliminate.",
    deleteRejected: "LexO-server non ha eliminato l’intervista",
    importReportTitle: "ESITI IMPORTAZIONE",
    importReportSummary: (completed: number, total: number, problems: number) =>
      problems > 0
        ? `Caricati ${completed} di ${total} file, ${problems} con problemi.`
        : `Caricati ${completed} di ${total} file.`,
    bulkError: (detail: string) => `Errore durante l’importazione bulk: ${detail}`,
    bulkNoJob: "LexO-server non ha restituito l’identificativo del bulk",
    bulkNotReady: "I testi convertiti non sono ancora disponibili nell’archivio",
    bulkAttestationsPartial: (count: number, detail: string) =>
      `${count} attestazioni non salvate: ${detail}`,
    bulkTimeout: "Tempo massimo superato durante l’importazione bulk",
    loadError: (detail: string) => `Impossibile caricare l’archivio (${detail}).`,
    selectAria: "Attiva o disattiva la selezione multipla delle interviste",
    selectTitle: "Seleziona interviste da eliminare",
    selectedCount: (n: number) => `${n} selezionate`,
    fileCount: (n: number) => `${n} interviste`,
    selectFirst: "Seleziona almeno una intervista",
    selectAll: "Tutte",
    clearSelection: "Nessuna",
    bulkDeleteConfirmTitle: (n: number) => `Eliminare ${n} interviste?`,
    bulkDeleteConfirmBody: "Verranno eliminati i testi e tutte le annotazioni associate. L’operazione non può essere annullata.",
    bulkDeleteActiveWarning: "Attenzione: è inclusa l’intervista correntemente aperta.",
    bulkDeleteProgress: (deleted: number, total: number) => `Eliminate ${deleted} di ${total}…`,
    uploadProgress: (uploaded: number, total: number) => `Caricati ${uploaded} di ${total}…`,
    bulkDeleteSuccess: (n: number) => `${n} interviste eliminate.`,
    bulkDeletePartial: (deleted: number, failed: number, detail: string) =>
      `Eliminate ${deleted} interviste, ${failed} non riuscite${detail ? `. ${detail}` : "."}`,
    bulkDeleteError: (detail: string) => `Errore durante l’eliminazione bulk: ${detail}`,
  },
  search: {
    formaButton: "Forma",
    conceptButton: "Concetto",
    entryButton: "Termine",
    formaTitle: "Ricerca per forma attestata",
    conceptTitle: "Ricerca per concetto",
    entryTitle: "Ricerca per termine",
    soon: "In preparazione",
    formaPlaceholder: "Forma da cercare…",
    formaHint: "* qualsiasi sequenza · ? un carattere · maiuscole/minuscole ignorate",
    run: "Cerca",
    loading: "Ricerca in corso…",
    emptyPrompt: "Configura la ricerca e premi «Cerca».",
    conceptPlaceholder: "Cerca un concetto…",
    conceptHint: "Scegli una voce del repertorio; il numero accanto indica le attestazioni presenti.",
    entryPlaceholder: "Cerca un termine…",
    entryHint: "Scegli un’entrata del lessico: la ricerca copre le attestazioni dei suoi sensi.",
    noMatch: "Nessuna voce del repertorio corrisponde.",
    noResults: "Nessun risultato per la ricerca corrente.",
    colDoc: "Documento",
    colLeft: "Contesto sinistro",
    colKeyword: "Keyword",
    colRight: "Contesto destro",
    colAnnotation: "Annotazione",
    colTerm: "Termine",
    colConcept: "Concetto",
    results: (n: number) => `${n} ${n === 1 ? "risultato" : "risultati"}`,
    page: (page: number, pages: number) => `Pagina ${page} di ${pages}`,
    error: (detail: string) => `Ricerca non riuscita: ${detail}`,
    relationAria: "Tipo di attestazioni da includere",
    relationAll: "Tutte",
    relationNarrative: "Solo narrative",
    relationParadigmatic: "Solo paradigmatiche",
    clearAria: "Cancella il contenuto del campo",
    onlyAnnotations: "Solo occorrenze in annotazioni",
  },
  document: {
    noInterview: "Nessuna intervista",
    textLoadError: (detail: string) => `Impossibile caricare il testo (${detail}).`,
    descriptionAria: (description: string) => `Descrizione: ${description}`,
    loadingInterview: "Caricamento intervista…",
    textUnavailable: "Testo non disponibile",
    retry: "Riprova",
    locusHint: "Modifica locus: trascina le maniglie oppure seleziona un nuovo intervallo",
    editHint: "Modalità modifica attestazione",
    selectHint: "Seleziona una porzione di testo con il mouse",
    savingAria: "Salvataggio annotazione in corso",
    countAll: (n: number) => `${n} annotazioni`,
    countFiltered: (filtered: number, total: number) => `${filtered} di ${total} annotazioni · Concetto`,
    filterRemoveTitle: "Rimuovi il filtro concetto",
    editAria: (label: string) => `Modifica attestazione: ${label}`,
    editTitle: "Modifica attestazione",
    locusSaveAria: "Salva i nuovi limiti dell’evidenziazione",
    locusEditAria: "Modifica i limiti dell’evidenziazione",
    locusSaveTitle: "Salva nuovo start ed end",
    locusEditTitle: "Modifica start ed end",
    eraseAria: "Elimina l’intera attestazione",
    eraseTitle: "Elimina attestazione e concetti associati",
  },
  concepts: {
    sidebarAria: "Repertorio dei concetti",
    title: "Concetti",
    addAria: "Aggiungi lexical concept",
    addTitle: "Aggiungi lexical concept",
    creatingAria: "Creazione del concetto in corso",
    renamingAria: "Rinomina del concetto in corso",
    reloadAria: "Ricarica concetti da LexO-server",
    reloadTitle: "Ricarica concetti",
    count: (n: number) => `${n} voci`,
    searchPlaceholder: "Cerca concetto…",
    searchAria: "Cerca concetto per label",
    loading: "Caricamento da LexO-server…",
    unavailable: "Repertorio non disponibile",
    newPlaceholder: "Scrivi il nome del concetto",
    newNameAria: "Nome del nuovo lexical concept",
    confirmCreateAria: "Conferma creazione",
    cancelCreateAria: "Annulla creazione",
    editAria: (label: string) => `Modifica ${label}`,
    confirmRenameAria: "Conferma rinomina",
    cancelRenameAria: "Annulla rinomina",
    clickSelect: "Clic per selezionare il concetto",
    clickFilter: "Clic per filtrare le annotazioni per concetto",
    emptyAll: "Nessun concetto trovato.",
    emptyFilter: "Nessun concetto corrispondente.",
    menuAria: "Menu concetto",
    menuDelete: "Elimina",
    deleteConfirmTitle: (label: string) => `Eliminare il concetto “${label}”?`,
    deleteConfirmBody: "Il concetto verrà rimosso dal repertorio. L’operazione non può essere annullata.",
    exists: (label: string) => `Esiste già un concetto chiamato “${label}”.`,
    created: (label: string) => `Concetto “${label}” creato correttamente.`,
    createError: (detail: string) => `Il concetto non è stato creato: ${detail}`,
    renamed: (label: string) => `Concetto rinominato in “${label}”.`,
    renameError: (detail: string) => `La label non è stata modificata a causa di un errore in LexO-server: ${detail}`,
    inUse: (label: string) => `Il concetto “${label}” è usato e non può essere eliminato.`,
    deleted: (label: string) => `Concetto “${label}” eliminato.`,
    deleteError: (detail: string) => `Il concetto non è stato eliminato: ${detail}`,
    loadError: (detail: string) => `Impossibile caricare i concetti (${detail})`,
    unknownError: "errore sconosciuto",
  },
  entry: {
    legend: "Entrata lessicale",
    aria: (label: string) => `Entrata lessicale per ${label}`,
    loading: "Caricamento…",
    choose: "Scegli un’entrata…",
    none: "Nessuna entrata associata",
    unavailable: "Entrate non disponibili",
    retry: "Riprova",
    sensesLoading: "Caricamento metadata dei sensi…",
    sensesError: "Metadata non disponibili.",
    noSenses: "Nessun senso narrativo o paradigmatico trovato.",
    noNarrative: "Senso narrativo non disponibile.",
    noParadigmatic: "Senso paradigmatico non disponibile.",
  },
  panels: {
    relationLegend: "Relazione",
    polarityLegend: "Polarità",
    polarityAria: (label: string) => `Polarità ${label}`,
    definitionLegend: "Tipo di definizione",
    definitionAria: (label: string) => `Tipo di definizione: ${label}`,
    evidenceLegend: "Tipo di evidenza",
    usageLegend: "Modi d’uso",
    usageAria: (label: string) => `Modo d’uso per ${label}`,
    noteLegend: "Note",
    noteAria: (label: string) => `Note per ${label}`,
    notePlaceholder: "Aggiungi una nota…",
  },
  options: {
    relation: { paradigmatico: "Paradigmatico", narrativo: "Narrativo" },
    polarity: { negative: "Negative", neutral: "Neutral", positive: "Positive" },
    definition: {
      sinonimo: "Sinonimo",
      parafrasi: "Parafrasi",
      "esempio-prototipo": "Esempio prototipo",
      "associazione-concettuale": "Associazione concettuale",
    },
    evidence: { nessuno: "Nessuno", attestato: "Attestato", inferito: "Inferito" },
    usageNone: "Nessuno",
  },
  action: {
    save: "Salva annotazione",
    confirm: "Conferma modifiche",
    savingAria: "Salvataggio in corso",
    oneSelected: "concetto selezionato",
    manySelected: "concetti selezionati",
    editCompleteNew: "Completa i dati obbligatori dei nuovi concetti",
    editModify: "Modifica concetti o attributi",
    createComplete: "Completa entrata, relazione e attributi di ogni concetto",
    createChoose: "Scegli almeno un concetto",
  },
  modals: {
    kicker: "ELIMINAZIONE",
    cancel: "Annulla",
    delete: "Elimina",
    attestationTitle: "Eliminare l’attestazione?",
    attestationBody: (text: string) =>
      `Verranno eliminate l’attestazione “${text}” e i concetti ad essa associati. L’operazione non può essere annullata.`,
    interviewTitle: (name: string) => `Eliminare l’intervista “${name}”?`,
    interviewBody: "Verranno eliminati il testo e le attestazioni associate. L’operazione non può essere annullata.",
    growlClose: "Chiudi messaggio",
    dirtyKicker: "MODIFICHE NON SALVATE",
    dirtyTitle: "Scartare le modifiche?",
    dirtyBody: "L’annotazione corrente ha modifiche non salvate: procedendo verranno perse.",
    dirtyConfirm: "Scarta e procedi",
    passwordKicker: "AREA RISERVATA",
    passwordTitle: "Costruisci Dizionario",
    passwordBody: "L’area di annotazione è riservata: inserisci la password per accedere.",
    passwordPlaceholder: "Password",
    passwordAria: "Password dell’area riservata",
    passwordConfirm: "Accedi",
    passwordError: "Password non corretta.",
    passwordUnavailable: "Verifica non disponibile: apri il sito in HTTPS o da localhost.",
  },
  messages: {
    attestationsLoadError: (detail: string) => `Impossibile caricare le attestazioni: ${detail}`,
    senseMetadataError: (detail: string) => `Impossibile caricare i metadata dei sensi: ${detail}`,
    createNeedOptions: "Scegli paradigmatico o narrativo e completa gli attributi richiesti per ogni concetto.",
    createNoContext: "Non è possibile creare l’attestazione: l’intervista non contiene l’IRI del nif:Context.",
    createConceptGone: "Non è possibile creare l’attestazione: uno dei concetti selezionati non è più disponibile.",
    createPartialSenses: (failed: number, labels: string) =>
      `Attestazione creata, ma non è stato possibile aggiornare ${failed} concetti narrativi (${labels}).`,
    createReloadError: (detail: string) => `Attestazione creata, ma non è stato possibile ricaricare l’elenco (${detail}).`,
    saved: "Annotazione salvata.",
    saveError: (detail: string) => `Errore durante il salvataggio dell’annotazione: ${detail}`,
    locusNoText: "Non è possibile modificare il locus: mancano i dati del testo su LexO-server.",
    locusNoAttestations: "Non è possibile modificare il locus: mancano gli IRI delle attestazioni selezionate.",
    locusSaved: (start: number, end: number) => `Nuovo locus salvato: start ${start}, end ${end}.`,
    locusError: (detail: string) => `Errore durante la modifica del locus: ${detail}`,
    updateNeedOptions: "Completa entrata, relazione e attributi obbligatori dei nuovi concetti.",
    updateNoText: "Non è possibile modificare l’attestazione: mancano i dati del testo su LexO-server.",
    updateNoLocus: "Non è possibile modificare l’attestazione: manca l’IRI del locus.",
    updateConceptGone: "Uno dei nuovi concetti selezionati non è più disponibile.",
    updatePartialFailures: (failed: number, total: number, details: string) =>
      `${failed} di ${total} aggiornamenti non riusciti: ${details}`,
    updateRemoveError: (detail: string) => `Rimozione: ${detail}`,
    updateAddError: (detail: string) => `Aggiunta: ${detail}`,
    updateSenseLinkError: (label: string, detail: string) => `Collegamento del senso per ${label}: ${detail}`,
    updateMetadataError: (detail: string) => `Aggiornamento metadati: ${detail}`,
    updated: "Modifiche all’attestazione salvate.",
    updateError: (detail: string) => `Errore durante la modifica dell’attestazione: ${detail}`,
    deleteNoContext: "Non è possibile eliminare l’attestazione: l’intervista non contiene l’IRI del nif:Context.",
    deleteNoLocus: "Non è possibile eliminare l’attestazione: il servizio non ha restituito l’IRI del locus.",
    deleted: "Attestazione eliminata.",
    deleteError: (detail: string) => `Errore durante l’eliminazione dell’attestazione: ${detail}`,
  },
  cq: {
    kicker: "COMPETENCY QUESTIONS",
    title: "Interrogazioni",
    intro: "Esplora il dizionario narrativo attraverso le competency questions: collegano entrate lessicali, concetti narrativi, evidenza del corpus e variazione tra i parlanti.",
    viewQuery: "Visualizza query",
    comingSoon: "In preparazione",
    comingSoonTitle: "La query SPARQL di questa competency question è in fase di definizione",
    queryPreview: "Anteprima query",
    queryPreviewEmpty: "Seleziona una competency question per visualizzarne la formulazione in linguaggio naturale e la query SPARQL corrispondente.",
    naturalLanguage: "Competency question",
    sparqlLabel: "Query SPARQL",
    cq2PreviewNote: "Query di supporto dei passaggi per concetto e polarità; la query dedicata è in fase di definizione.",
    aboutTitle: "Informazioni su queste query",
    aboutViewQuery: "«Visualizza query» mostra la formulazione SPARQL della competency question selezionata, a scopo di ispezione.",
    aboutOpenPanel: "Cliccando su una card si apre il pannello per esplorare i risultati della competency question.",
    aboutData: "Le query collegano entrate lessicali, concetti narrativi, evidenza del corpus e variazione tra i parlanti.",
    backToCards: "Torna alle competency questions",
    panelInProgressTitle: "Pannello in costruzione",
    panelInProgressBody: "Il pannello di analisi di questa competency question è in fase di sviluppo e sarà disponibile a breve.",
  },
  cq1: {
    panelTitle: "CQ1 – Concepts by polarity",
    entrySelectLabel: "Entrata lessicale",
    entryLoading: "Caricamento delle entrate lessicali…",
    entryEmpty: "Nessuna entrata lessicale disponibile",
    polarityViewLabel: "Polarità",
    polarityPositive: "Positiva",
    polarityNeutral: "Neutra",
    polarityNegative: "Negativa",
    sortLabel: "Ordina per",
    sortInterviewees: "Intervistati",
    sortOccurrences: "Occorrenze",
    sortAZ: "Alfabetico A–Z",
    sortZA: "Alfabetico Z–A",
    subtitle: (entry: string) => `Concetti associati ai narrative senses di «${entry}»`,
    positiveTitle: "Concetti positivi",
    negativeTitle: "Concetti negativi",
    neutralTitle: "Concetti neutri",
    paradigmaticTitle: "Concetti paradigmatici",
    conceptCount: (count: number) => `${count} concetti`,
    interviewees: "intervistati",
    occurrences: "occorrenze",
    showAll: (count: number) => `Mostra tutti (${count})`,
    showLess: "Mostra meno",
    panelEmpty: "Nessun concetto per questa polarità.",
    paradigmaticEmpty: "Nessun concetto paradigmatico per questa entrata.",
    distributionTitle: "Distribuzione complessiva",
    distributionConcepts: "concetti",
    detailTitle: "Dettaglio concetto",
    detailEmpty: "Seleziona un concetto per vederne i dettagli.",
    detailPolarity: "Polarità",
    detailInterviewees: "Intervistati distinti",
    detailOccurrences: "Occorrenze",
    detailTopAge: "Età più rappresentata",
    detailAgeBreakdown: "Ripartizione per età",
    detailSexBreakdown: "Ripartizione per genere",
    detailNotAvailable: "Non disponibile",
    detailParadigmaticNote: "Concetto paradigmatico: dettaglio demografico calcolato dalle attestazioni del corpus.",
    passagesTitle: "Passaggi del corpus",
    passagesEmpty: "Nessun passaggio disponibile per il concetto selezionato.",
    passageId: "ID",
    passageAge: "Età",
    passageSex: "Genere",
    passageText: "Passaggio",
    passagesShowAll: (count: number) => `Mostra tutti i passaggi (${count})`,
    exportCsv: "Esporta CSV",
    viewLabel: "Vista",
    viewList: "Lista",
    viewGraph: "Grafo",
    graphTitle: "Network graph dei concetti",
    graphLoading: "Caricamento del grafo…",
    graphEmpty: "Nessun concetto da mostrare per la configurazione selezionata.",
    graphNoEdges: "Nessuna co-occorrenza supera la soglia: i concetti sono mostrati senza relazioni.",
    graphHidden: (count: number) => `${count} concetti non mostrati per leggibilità.`,
    graphSectorParadigmatic: "Paradigmatici",
    graphLegendTitle: "Legenda",
    graphLegendSize: "Dimensione = occorrenze",
    graphLegendEdge: "Spessore = co-occorrenze",
    graphLegendCluster: "Area del cluster",
    graphZoomHint: "Shift + rotella per zoomare",
    graphNodeTopCooccurring: "Co-occorrenze principali",
    graphNodeIsolated: "Nessuna co-occorrenza nei turni selezionati.",
    graphTooltipEdgeForce: "Forza",
    graphTooltipEdgeUnit: "Unità",
    graphTooltipDocuments: "Documenti",
    graphUnitTurns: "turni di risposta",
    graphUnitDocuments: "documento (fallback)",
    graphFit: "Adatta",
    graphTooltipClose: "Chiudi",
    graphBackToList: "Torna alla lista",
    highlightCooccurring: "Evidenzia concetti co-occorrenti",
    clearHighlight: "Rimuovi evidenziazione",
    loading: "Caricamento…",
    errorPrefix: "Errore: ",
  },
  cq2: {
    panelTitle: "CQ2 – Corpus evidence",
    phraseBefore: "Tutti i passaggi in cui un narrative sense di",
    phraseMiddle: "è associato a un concetto di polarità",
    phraseAfter: ".",
    filterAge: "Età",
    filterAllAges: "Tutte le età",
    filterGender: "Genere",
    filterAllGenders: "Tutti",
    sortLabel: "Ordina per",
    sortAgeAsc: "Età (crescente)",
    sortAgeDesc: "Età (decrescente)",
    sortIdAZ: "ID (A–Z)",
    configTitle: "Configurazione della ricerca",
    configEntry: "Entrata lessicale",
    configPolarity: "Polarità",
    configResults: "Passaggi restituiti",
    configAge: "Filtro età",
    configGender: "Filtro genere",
    configAll: "Tutti",
    conceptsTitle: (polarity: string) => `Concetti ${polarity.toLowerCase()} nei risultati`,
    conceptsCount: (count: number) => `${count} passaggi`,
    passagesTitle: "Passaggi del corpus",
    passageId: "ID",
    passageText: "Passaggio",
    passageConcept: "Concetto",
    passagePolarity: "Polarità",
    passageAge: "Età",
    passageSex: "Genere",
    passagesRange: (from: number, to: number, total: number) => `${from}–${to} di ${total}`,
    prevPage: "Pagina precedente",
    nextPage: "Pagina successiva",
    exportCsv: "Esporta risultati",
    expandHint: "Clicca un passaggio per il contesto completo e i metadati del parlante.",
    expandedContext: "Contesto",
    expandedSpeakerSex: "Sesso",
    expandedSpeakerAge: "Età",
    expandedSpeakerResidence: "Residenza",
    emptyResults: "Nessun passaggio per i parametri selezionati.",
    emptyHint: "Cambia entrata lessicale, polarità o filtri.",
    loading: "Caricamento del corpus…",
    errorPrefix: "Errore: ",
  },
  cq3: {
    panelTitle: "CQ3 – Speaker variation",
    entrySelectLabel: "Entrata lessicale",
    conceptSelectLabel: "Concetti",
    conceptAll: "Tutti i concetti",
    conceptOne: (label: string) => `Concetto: ${label}`,
    addConcept: "Aggiungi concetto…",
    noConceptMatch: "Nessun concetto corrisponde al filtro.",
    removeConcept: "Rimuovi",
    allAgeGroups: "Tutti i gruppi di età",
    allGenders: "Tutti i generi",
    filterAge: "Gruppi di età",
    filterGender: "Genere",
    subtitle: (entry: string) => `Distribuzione dei concetti associati a «${entry}» tra i parlanti`,
    viewLabel: "Vista",
    viewBars: "Barre",
    viewHeatmap: "Heatmap",
    viewTable: "Tabella",
    sortLabel: "Ordina concetti",
    sortPctDesc: "Frequenza (decrescente)",
    sortAZ: "Alfabetico A–Z",
    band12: "12–16",
    band17: "17–21",
    bandGt21: ">21",
    female: "Femmine",
    male: "Maschi",
    percentage: (value: number) => `${value}%`,
    denominatorNote: "Percentuali calcolate sulla popolazione di intervistati del gruppo nel corpus (interviste con età e sesso validi).",
    chartTitle: "Distribuzione per fascia d'età e genere",
    chartEmpty: "Nessun dato per il concetto selezionato.",
    heatmapTitle: "Heatmap concetti × gruppo",
    heatmapHint: "Clicca una cella per i passaggi del gruppo.",
    tableTitle: "Dati per gruppo",
    tableBand: "Fascia",
    tableFemale: "Femmine",
    tableMale: "Maschi",
    tableTotal: "Totale",
    tableN: (count: number) => `${count.toLocaleString("it-IT")} intervistati`,
    passagesTitle: "Passaggi del gruppo",
    passagesEmpty: "Seleziona una combinazione (cella heatmap o barra) per vedere i passaggi.",
    backToOverview: "‹ Torna alla panoramica",
    loading: "Caricamento…",
    errorPrefix: "Errore: ",
  },
};

export type Dict = typeof it;

const en: Dict = {
  nav: {
    items: [
      "The Project",
      "Statistics",
      "Explore Dictionary",
      "Explore Dictionary",
      "Dictionary Builder",
      "Scientific Results",
      "Contacts",
    ],
    reservedAria: (item: string) => `${item}, restricted area requiring authentication`,
    reservedTitle: "Restricted area: password required",
    mainAria: "Main navigation",
    versionTitle: (version: string) => `Interface version ${version}`,
    switchAria: "Language selection",
  },
  header: {
    eyebrow: "Linguistic Research and Social Innovation",
    partnerAria: "Project partners",
  },
  workspace: {
    sectionAria: "Interview annotation",
  },
  archive: {
    title: "Interviews",
    uploadAria: "Bulk upload interviews",
    uploadTitle: "Bulk upload interviews",
    deleteAria: "Delete the displayed interview",
    reloadAria: "Reload archive from LexO-server",
    reloadTitle: "Reload archive",
    searchPlaceholder: "Search interviews…",
    searchAria: "Search interviews by file name",
    loading: "Loading from LexO-server…",
    unavailable: "Archive unavailable",
    emptySearch: "No interview found.",
    serverStats: (tokens: string, sentences: number, annotations: number) =>
      `${tokens} tokens · ${sentences} sentences · ${annotations} annotations`,
    localStats: (chars: string, annotations: number) =>
      `${chars} characters · ${annotations} annotations`,
    deleteConfirmTitle: (name: string) => `Delete interview “${name}”?`,
    deleteConfirmBody: "The text and its attestations will be deleted. This action cannot be undone.",
    deleteSuccess: (name: string) => `Interview “${name}” deleted.`,
    deleteError: (detail: string) => `The interview was not deleted: ${detail}`,
    deleteNotAllowed: "Only interviews stored on LexO-server can be deleted.",
    deleteRejected: "LexO-server did not delete the interview",
    bulkError: (detail: string) => `Error during bulk import: ${detail}`,
    bulkNoJob: "LexO-server did not return the bulk identifier",
    bulkNotReady: "The converted texts are not yet available in the archive",
    bulkAttestationsPartial: (count: number, detail: string) =>
      `${count} attestations not saved: ${detail}`,
    bulkTimeout: "Maximum time exceeded during bulk import",
    loadError: (detail: string) => `Unable to load the archive (${detail}).`,
    selectAria: "Toggle multi-selection of interviews",
    selectTitle: "Select interviews to delete",
    selectedCount: (n: number) => `${n} selected`,
    fileCount: (n: number) => `${n} interviews`,
    selectFirst: "Select at least one interview",
    selectAll: "All",
    clearSelection: "Clear",
    bulkDeleteConfirmTitle: (n: number) => `Delete ${n} interviews?`,
    bulkDeleteConfirmBody: "The texts and all their annotations will be deleted. This action cannot be undone.",
    bulkDeleteActiveWarning: "Warning: the currently open interview is included.",
    bulkDeleteProgress: (deleted: number, total: number) => `Deleted ${deleted} of ${total}…`,
    uploadProgress: (uploaded: number, total: number) => `Uploaded ${uploaded} of ${total}…`,
    importReportTitle: "IMPORT REPORT",
    importReportSummary: (completed: number, total: number, problems: number) =>
      problems > 0
        ? `Uploaded ${completed} of ${total} files, ${problems} with problems.`
        : `Uploaded ${completed} of ${total} files.`,
    bulkDeleteSuccess: (n: number) => `${n} interviews deleted.`,
    bulkDeletePartial: (deleted: number, failed: number, detail: string) =>
      `${deleted} interviews deleted, ${failed} failed${detail ? `. ${detail}` : "."}`,
    bulkDeleteError: (detail: string) => `Error during bulk deletion: ${detail}`,
  },
  search: {
    formaButton: "Form",
    conceptButton: "Concept",
    entryButton: "Entry",
    formaTitle: "Search by attested form",
    conceptTitle: "Search by concept",
    entryTitle: "Search by lexical entry",
    soon: "Coming soon",
    formaPlaceholder: "Form to search…",
    formaHint: "* any sequence · ? one character · case-insensitive",
    run: "Search",
    loading: "Searching…",
    emptyPrompt: "Set up the search and press “Search”.",
    conceptPlaceholder: "Search a concept…",
    conceptHint: "Pick a repertory entry; the number is its attestation count.",
    entryPlaceholder: "Search a lexical entry…",
    entryHint: "Pick a lexicon entry: the search covers the attestations of its senses.",
    noMatch: "No repertory entry matches.",
    noResults: "No results for the current search.",
    colDoc: "Document",
    colLeft: "Left context",
    colKeyword: "Keyword",
    colRight: "Right context",
    colAnnotation: "Annotation",
    colTerm: "Entry",
    colConcept: "Concept",
    results: (n: number) => `${n} ${n === 1 ? "result" : "results"}`,
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
    error: (detail: string) => `Search failed: ${detail}`,
    relationAria: "Type of attestations to include",
    relationAll: "All",
    relationNarrative: "Narrative only",
    relationParadigmatic: "Paradigmatic only",
    clearAria: "Clear the field",
    onlyAnnotations: "Only occurrences within annotations",
  },
  document: {
    noInterview: "No interview",
    textLoadError: (detail: string) => `Unable to load the text (${detail}).`,
    descriptionAria: (description: string) => `Description: ${description}`,
    loadingInterview: "Loading interview…",
    textUnavailable: "Text unavailable",
    retry: "Retry",
    locusHint: "Locus editing: drag the handles or select a new range",
    editHint: "Annotation editing mode",
    selectHint: "Select a portion of text with the mouse",
    savingAria: "Saving annotation",
    countAll: (n: number) => `${n} annotations`,
    countFiltered: (filtered: number, total: number) => `${filtered} of ${total} annotations · Concept`,
    filterRemoveTitle: "Remove concept filter",
    editAria: (label: string) => `Edit attestation: ${label}`,
    editTitle: "Edit attestation",
    locusSaveAria: "Save the new highlight boundaries",
    locusEditAria: "Edit the highlight boundaries",
    locusSaveTitle: "Save new start and end",
    locusEditTitle: "Edit start and end",
    eraseAria: "Delete the entire attestation",
    eraseTitle: "Delete attestation and associated concepts",
  },
  concepts: {
    sidebarAria: "Concept repertory",
    title: "Concepts",
    addAria: "Add lexical concept",
    addTitle: "Add lexical concept",
    creatingAria: "Creating concept",
    renamingAria: "Renaming concept",
    reloadAria: "Reload concepts from LexO-server",
    reloadTitle: "Reload concepts",
    count: (n: number) => `${n} entries`,
    searchPlaceholder: "Search concepts…",
    searchAria: "Search concepts by label",
    loading: "Loading from LexO-server…",
    unavailable: "Repertory unavailable",
    newPlaceholder: "Type the concept name",
    newNameAria: "Name of the new lexical concept",
    confirmCreateAria: "Confirm creation",
    cancelCreateAria: "Cancel creation",
    editAria: (label: string) => `Edit ${label}`,
    confirmRenameAria: "Confirm rename",
    cancelRenameAria: "Cancel rename",
    clickSelect: "Click to select the concept",
    clickFilter: "Click to filter annotations by concept",
    emptyAll: "No concept found.",
    emptyFilter: "No matching concept.",
    menuAria: "Concept menu",
    menuDelete: "Delete",
    deleteConfirmTitle: (label: string) => `Delete concept “${label}”?`,
    deleteConfirmBody: "The concept will be removed from the repertory. This action cannot be undone.",
    exists: (label: string) => `A concept named “${label}” already exists.`,
    created: (label: string) => `Concept “${label}” created successfully.`,
    createError: (detail: string) => `The concept was not created: ${detail}`,
    renamed: (label: string) => `Concept renamed to “${label}”.`,
    renameError: (detail: string) => `The label was not changed due to a LexO-server error: ${detail}`,
    inUse: (label: string) => `The concept “${label}” is in use and cannot be deleted.`,
    deleted: (label: string) => `Concept “${label}” deleted.`,
    deleteError: (detail: string) => `The concept was not deleted: ${detail}`,
    loadError: (detail: string) => `Unable to load concepts (${detail})`,
    unknownError: "unknown error",
  },
  entry: {
    legend: "Lexical entry",
    aria: (label: string) => `Lexical entry for ${label}`,
    loading: "Loading…",
    choose: "Choose an entry…",
    none: "No associated entry",
    unavailable: "Entries unavailable",
    retry: "Retry",
    sensesLoading: "Loading sense metadata…",
    sensesError: "Metadata unavailable.",
    noSenses: "No narrative or paradigmatic sense found.",
    noNarrative: "Narrative sense unavailable.",
    noParadigmatic: "Paradigmatic sense unavailable.",
  },
  panels: {
    relationLegend: "Relation",
    polarityLegend: "Polarity",
    polarityAria: (label: string) => `Polarity ${label}`,
    definitionLegend: "Definition type",
    definitionAria: (label: string) => `Definition type: ${label}`,
    evidenceLegend: "Evidence type",
    usageLegend: "Usage modes",
    usageAria: (label: string) => `Usage mode for ${label}`,
    noteLegend: "Notes",
    noteAria: (label: string) => `Notes for ${label}`,
    notePlaceholder: "Add a note…",
  },
  options: {
    relation: { paradigmatico: "Paradigmatic", narrativo: "Narrative" },
    polarity: { negative: "Negative", neutral: "Neutral", positive: "Positive" },
    definition: {
      sinonimo: "Synonym",
      parafrasi: "Paraphrase",
      "esempio-prototipo": "Prototype example",
      "associazione-concettuale": "Conceptual association",
    },
    evidence: { nessuno: "None", attestato: "Attested", inferito: "Inferred" },
    usageNone: "None",
  },
  action: {
    save: "Save annotation",
    confirm: "Confirm changes",
    savingAria: "Saving",
    oneSelected: "concept selected",
    manySelected: "concepts selected",
    editCompleteNew: "Complete the required data of the new concepts",
    editModify: "Edit concepts or attributes",
    createComplete: "Complete entry, relation and attributes of each concept",
    createChoose: "Choose at least one concept",
  },
  modals: {
    kicker: "DELETION",
    cancel: "Cancel",
    delete: "Delete",
    attestationTitle: "Delete this attestation?",
    attestationBody: (text: string) =>
      `The attestation “${text}” and its associated concepts will be deleted. This action cannot be undone.`,
    interviewTitle: (name: string) => `Delete interview “${name}”?`,
    interviewBody: "The text and its attestations will be deleted. This action cannot be undone.",
    growlClose: "Close message",
    dirtyKicker: "UNSAVED CHANGES",
    dirtyTitle: "Discard changes?",
    dirtyBody: "The current annotation has unsaved changes: continuing will lose them.",
    dirtyConfirm: "Discard and proceed",
    passwordKicker: "RESTRICTED AREA",
    passwordTitle: "Build Dictionary",
    passwordBody: "The annotation area is restricted: enter the password to continue.",
    passwordPlaceholder: "Password",
    passwordAria: "Restricted area password",
    passwordConfirm: "Sign in",
    passwordError: "Incorrect password.",
    passwordUnavailable: "Verification unavailable: open the site over HTTPS or from localhost.",
  },
  messages: {
    attestationsLoadError: (detail: string) => `Unable to load attestations: ${detail}`,
    senseMetadataError: (detail: string) => `Unable to load sense metadata: ${detail}`,
    createNeedOptions: "Choose paradigmatic or narrative and complete the required attributes for each concept.",
    createNoContext: "Cannot create the attestation: the interview has no nif:Context IRI.",
    createConceptGone: "Cannot create the attestation: one of the selected concepts is no longer available.",
    createPartialSenses: (failed: number, labels: string) =>
      `Attestation created, but ${failed} narrative concepts could not be updated (${labels}).`,
    createReloadError: (detail: string) => `Attestation created, but the list could not be reloaded (${detail}).`,
    saved: "Annotation saved.",
    saveError: (detail: string) => `Error while saving the annotation: ${detail}`,
    locusNoText: "Cannot edit the locus: text data is missing on LexO-server.",
    locusNoAttestations: "Cannot edit the locus: the selected attestations have no IRIs.",
    locusSaved: (start: number, end: number) => `New locus saved: start ${start}, end ${end}.`,
    locusError: (detail: string) => `Error while editing the locus: ${detail}`,
    updateNeedOptions: "Complete the entry, relation and required attributes of the new concepts.",
    updateNoText: "Cannot edit the attestation: text data is missing on LexO-server.",
    updateNoLocus: "Cannot edit the attestation: the locus IRI is missing.",
    updateConceptGone: "One of the newly selected concepts is no longer available.",
    updatePartialFailures: (failed: number, total: number, details: string) =>
      `${failed} of ${total} updates failed: ${details}`,
    updateRemoveError: (detail: string) => `Removal: ${detail}`,
    updateAddError: (detail: string) => `Addition: ${detail}`,
    updateSenseLinkError: (label: string, detail: string) => `Sense linking for ${label}: ${detail}`,
    updateMetadataError: (detail: string) => `Metadata update: ${detail}`,
    updated: "Attestation changes saved.",
    updateError: (detail: string) => `Error while editing the attestation: ${detail}`,
    deleteNoContext: "Cannot delete the attestation: the interview has no nif:Context IRI.",
    deleteNoLocus: "Cannot delete the attestation: the service did not return the locus IRI.",
    deleted: "Attestation deleted.",
    deleteError: (detail: string) => `Error while deleting the attestation: ${detail}`,
  },
  cq: {
    kicker: "COMPETENCY QUESTIONS",
    title: "Queries",
    intro: "Explore the narrative dictionary through competency questions: they connect lexical entries, narrative concepts, corpus evidence and speaker variation.",
    viewQuery: "View query",
    comingSoon: "Coming soon",
    comingSoonTitle: "The SPARQL query for this competency question is still being defined",
    queryPreview: "Query preview",
    queryPreviewEmpty: "Select a competency question to see its natural language formulation and the corresponding SPARQL query.",
    naturalLanguage: "Competency question",
    sparqlLabel: "SPARQL query",
    cq2PreviewNote: "Support query for passages by concept and polarity; the dedicated query is still being defined.",
    aboutTitle: "About these queries",
    aboutViewQuery: "“View query” shows the SPARQL formulation of the selected competency question, for inspection.",
    aboutOpenPanel: "Clicking a card opens the panel to explore the results of the competency question.",
    aboutData: "The questions connect lexical entries, narrative concepts, corpus evidence and speaker variation.",
    backToCards: "Back to competency questions",
    panelInProgressTitle: "Panel under construction",
    panelInProgressBody: "The analysis panel for this competency question is under development and will be available soon.",
  },
  cq1: {
    panelTitle: "CQ1 – Concepts by polarity",
    entrySelectLabel: "Lexical entry",
    entryLoading: "Loading lexical entries…",
    entryEmpty: "No lexical entry available",
    polarityViewLabel: "Polarity",
    polarityPositive: "Positive",
    polarityNeutral: "Neutral",
    polarityNegative: "Negative",
    sortLabel: "Sort by",
    sortInterviewees: "Interviewees",
    sortOccurrences: "Occurrences",
    sortAZ: "Alphabetical A–Z",
    sortZA: "Alphabetical Z–A",
    subtitle: (entry: string) => `Concepts associated with the narrative senses of “${entry}”`,
    positiveTitle: "Positive concepts",
    negativeTitle: "Negative concepts",
    neutralTitle: "Neutral concepts",
    paradigmaticTitle: "Paradigmatic concepts",
    conceptCount: (count: number) => `${count} concepts`,
    interviewees: "interviewees",
    occurrences: "occurrences",
    showAll: (count: number) => `Show all (${count})`,
    showLess: "Show less",
    panelEmpty: "No concepts for this polarity.",
    paradigmaticEmpty: "No paradigmatic concepts for this entry.",
    distributionTitle: "Overall distribution",
    distributionConcepts: "concepts",
    detailTitle: "Concept details",
    detailEmpty: "Select a concept to see its details.",
    detailPolarity: "Polarity",
    detailInterviewees: "Distinct interviewees",
    detailOccurrences: "Occurrences",
    detailTopAge: "Most represented age",
    detailAgeBreakdown: "Age breakdown",
    detailSexBreakdown: "Gender breakdown",
    detailNotAvailable: "Not available",
    detailParadigmaticNote: "Paradigmatic concept: demographic detail computed from corpus attestations.",
    passagesTitle: "Corpus passages",
    passagesEmpty: "No passages available for the selected concept.",
    passageId: "ID",
    passageAge: "Age",
    passageSex: "Gender",
    passageText: "Passage",
    passagesShowAll: (count: number) => `Show all passages (${count})`,
    exportCsv: "Export CSV",
    viewLabel: "View",
    viewList: "List",
    viewGraph: "Graph",
    graphTitle: "Concept network graph",
    graphLoading: "Loading the graph…",
    graphEmpty: "No concepts to display for the current configuration.",
    graphNoEdges: "No co-occurrence passes the threshold: concepts are shown without relations.",
    graphHidden: (count: number) => `${count} concepts not shown for readability.`,
    graphSectorParadigmatic: "Paradigmatic",
    graphLegendTitle: "Legend",
    graphLegendSize: "Size = occurrences",
    graphLegendEdge: "Thickness = co-occurrence",
    graphLegendCluster: "Cluster area",
    graphZoomHint: "Shift + wheel to zoom",
    graphNodeTopCooccurring: "Main co-occurrences",
    graphNodeIsolated: "No co-occurrence in the selected turns.",
    graphTooltipEdgeForce: "Strength",
    graphTooltipEdgeUnit: "Unit",
    graphTooltipDocuments: "Documents",
    graphUnitTurns: "respondent turns",
    graphUnitDocuments: "document (fallback)",
    graphFit: "Fit",
    graphTooltipClose: "Close",
    graphBackToList: "Back to list",
    highlightCooccurring: "Highlight co-occurring concepts",
    clearHighlight: "Clear highlight",
    loading: "Loading…",
    errorPrefix: "Error: ",
  },
  cq2: {
    panelTitle: "CQ2 – Corpus evidence",
    phraseBefore: "All passages in which a narrative sense of",
    phraseMiddle: "is associated with a concept of",
    phraseAfter: " polarity.",
    filterAge: "Age",
    filterAllAges: "All ages",
    filterGender: "Gender",
    filterAllGenders: "All",
    sortLabel: "Sort by",
    sortAgeAsc: "Age (ascending)",
    sortAgeDesc: "Age (descending)",
    sortIdAZ: "ID (A–Z)",
    configTitle: "Search configuration",
    configEntry: "Lexical entry",
    configPolarity: "Polarity",
    configResults: "Passages returned",
    configAge: "Age filter",
    configGender: "Gender filter",
    configAll: "All",
    conceptsTitle: (polarity: string) => `${polarity} concepts in results`,
    conceptsCount: (count: number) => `${count} passages`,
    passagesTitle: "Corpus passages",
    passageId: "ID",
    passageText: "Passage",
    passageConcept: "Concept",
    passagePolarity: "Polarity",
    passageAge: "Age",
    passageSex: "Gender",
    passagesRange: (from: number, to: number, total: number) => `${from}–${to} of ${total}`,
    prevPage: "Previous page",
    nextPage: "Next page",
    exportCsv: "Export results",
    expandHint: "Click a passage for the full context and the speaker metadata.",
    expandedContext: "Context",
    expandedSpeakerSex: "Sex",
    expandedSpeakerAge: "Age",
    expandedSpeakerResidence: "Residence",
    emptyResults: "No passages for the selected parameters.",
    emptyHint: "Change lexical entry, polarity or filters.",
    loading: "Loading the corpus…",
    errorPrefix: "Error: ",
  },
  cq3: {
    panelTitle: "CQ3 – Speaker variation",
    entrySelectLabel: "Lexical entry",
    conceptSelectLabel: "Concepts",
    conceptAll: "All concepts",
    conceptOne: (label: string) => `Concept: ${label}`,
    addConcept: "Add concept…",
    noConceptMatch: "No concepts match the filter.",
    removeConcept: "Remove",
    allAgeGroups: "All age groups",
    allGenders: "All genders",
    filterAge: "Age groups",
    filterGender: "Gender",
    subtitle: (entry: string) => `Distribution of the concepts associated with “${entry}” across speakers`,
    viewLabel: "View",
    viewBars: "Bars",
    viewHeatmap: "Heatmap",
    viewTable: "Table",
    sortLabel: "Sort concepts",
    sortPctDesc: "Frequency (descending)",
    sortAZ: "Alphabetical A–Z",
    band12: "12–16",
    band17: "17–21",
    bandGt21: ">21",
    female: "Female",
    male: "Male",
    percentage: (value: number) => `${value}%`,
    denominatorNote: "Percentages computed over the group’s interviewee population in the corpus (interviews with valid age and sex).",
    chartTitle: "Distribution by age band and gender",
    chartEmpty: "No data for the selected concept.",
    heatmapTitle: "Heatmap concepts × group",
    heatmapHint: "Click a cell to see the group’s passages.",
    tableTitle: "Data per group",
    tableBand: "Band",
    tableFemale: "Female",
    tableMale: "Male",
    tableTotal: "Total",
    tableN: (count: number) => `${count} interviewees`,
    passagesTitle: "Group passages",
    passagesEmpty: "Select a combination (heatmap cell or bar) to see the passages.",
    backToOverview: "‹ Back to overview",
    loading: "Loading…",
    errorPrefix: "Error: ",
  },
};

export const dictionaries: Record<Lang, Dict> = { it, en };

export function detectInitialLang(): Lang {
  try {
    const stored = window.localStorage.getItem("fi-lang");
    if (stored === "it" || stored === "en") return stored;
  } catch {
  }
  return typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("en")
    ? "en"
    : "it";
}
